[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.151.0"


# Redirects for Decap CMS

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
