backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "books"
    label: "Books (Intro Pages)"
    folder: "content"
    # Matches content/book-*/_index.md
    path: "{{slug}}/_index"
    filter: {field: "title", value: "Book"} # Optional filter to avoid root _index.md
    extension: "md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Layout", name: "type", widget: "hidden", default: "docs"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number", default: 10}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "chapters"
    label: "Chapters (Content Pages)"
    folder: "content"
    # Matches content/book-*/chapter-*.md
    path: "{{dirname}}/{{slug}}"
    filter: {field: "type", value: "docs"}
    extension: "md"
    format: "frontmatter"
    create: true
    fields:
      - {label: "Layout", name: "type", widget: "hidden", default: "docs"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number", default: 10}
      - {label: "Body", name: "body", widget: "markdown"}
